bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

records/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_records, name='records'),
    path('<int:record_id>/', views.record_detail, name='record_detail'),
    path('add/', views.add_record, name='add_record'),
    path('edit/<int:record_id>/', views.edit_record, name='edit_record'),
    path('delete/<int:record_id>/', views.delete_record, name='delete_record'),
]

tonality/urls.py
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('records/', include('records.urls')),
    path('about/', include('about.urls')),
    path('faq/', include('faq.urls')),
    path('contact/', include('contact.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('robots.txt', TemplateView.as_view(
        template_name="robots.txt", content_type='text/plain')
        ),
    path('sitemap.xml', TemplateView.as_view(
        template_name="sitemap.xml", content_type='text/xml')
        ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Records(models.Model):

    class Meta:
        verbose_name = 'Records'

    category = models.ManyToManyField('Category', blank=True)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    releasedate = models.CharField(max_length=254, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    is_new_release = models.BooleanField(
        default=False,
        verbose_name="Is New Release")
    is_deal = models.BooleanField(default=False, verbose_name="Is Deal")
    is_clearance = models.BooleanField(
        default=False, verbose_name="Is Clearance")

    def __str__(self):
        return self.name

records/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Records, Category


class RecordForm(forms.ModelForm):

    class Meta:
        model = Records
        fields = '__all__'

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

records/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Records, Category
from .forms import RecordForm


def all_records(request):
    """View for all records"""

    records = Records.objects.all()
    query = None
    sort = None
    direction = None

    all_categories = Category.objects.all()

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                records = records.annotate(lower_name=Lower('name'))
            if sortkey == 'release':
                sortkey = 'releasedate'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            records = records.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            records = records.filter(category__name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q'].strip().lower()
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!"
                    )
                return redirect(reverse('records'))

            queries = (
                Q(name__icontains=query) |
                Q(description__icontains=query) |
                Q(category__name__icontains=query)
            )
            records = records.filter(queries).distinct()

    current_sorting = f'{sort}_{direction}'

    context = {
        'records': records,
        'search_term': query,
        'all_categories': all_categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'records/records.html', context)


def record_detail(request, record_id):
    """ A view to show individual record details """

    record = get_object_or_404(Records, pk=record_id)

    context = {
        'record': record,
    }

    return render(request, 'records/record_detail.html', context)


@login_required
def add_record(request):
    """ Add a record to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = RecordForm(request.POST, request.FILES)
        if form.is_valid():
            record = form.save()
            messages.success(request, 'Successfully added record!')
            return redirect(reverse('record_detail', args=[record.id]))
        else:
            messages.error(
                request,
                'Failed to add record. Please ensure the form is valid.'
                )
    else:
        form = RecordForm()

    template = 'records/add_record.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_record(request, record_id):
    """ Edit a record in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    record = get_object_or_404(Records, pk=record_id)
    if request.method == 'POST':
        form = RecordForm(request.POST, request.FILES, instance=record)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated record!')
            return redirect(reverse('record_detail', args=[record.id]))
        else:
            messages.error(
                request,
                'Failed to update record. Please ensure the form is valid.'
                )
    else:
        form = RecordForm(instance=record)
        messages.info(request, f'You are editing {record.name}')

    template = 'records/edit_record.html'
    context = {
        'form': form,
        'record': record,
    }

    return render(request, template, context)


@login_required
def delete_record(request, record_id):
    """ Delete a record from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    record = get_object_or_404(Records, pk=record_id)
    record.delete()
    messages.success(request, 'Record deleted!')
    return redirect(reverse('records'))

records/templates/records/add_record.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}


{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 mx-auto">
            <div class="product-details-container mb-5 mt-md-5">

                <p class="lead font-weight-bold">Add a Record</p>

                <div class="col-12">

                        
                        <form method="POST" action="/records/add/" class="form w-100 mb-2" enctype="multipart/form-data">

                            {% csrf_token %}
                                <label for="id_category" class="control-label ">
                                    Category
                                </label>
                                <p class="small text-light">Hold down CTRL to mark more than one category.</p>

                                <div class="controls">
                                    <div class="form-group">
                                        {{ form.category|attr:"class:form-control"|attr:"class:selectmultiple"|attr:"name=category"|attr:"id=id_category" }}
                                    </div>                                   
                                </div>

                                <label for="id_sku" class="control-label ">
                                    Sku
                                </label>
                                <div class="form-group">
                                    {{ form.sku|attr:"class:form-control"|attr:"placeholder:"|attr:"id=id_sku" }}
                                </div>
                                <input type="hidden" name="next" value="{{next}}" />

                                <label for="id_name" class="control-label requiredField">
                                    Name<span class="asteriskField">*</span>
                                </label>
                                <div class="form-group">
                                    {{ form.name|attr:"class:form-control"|attr:"placeholder:"|attr:"id=id_name"|attr:"required" }}
                                </div>
                                <input type="hidden" name="next" value="{{next}}" />

                                <label for="id_description" class="control-label requiredField">
                                    Description<span class="asteriskField">* </span> <span class="small text-light"> HTML here is ok.</span>
                                </label>

                                <div class="controls">
                                    <div class="form-group">
                                        {{ form.description|attr:"class:form-control"|attr:"cols:40"|attr:"rows=10"|attr:"id=id_description"|attr:"required" }}
                                    </div>
                                    <input type="hidden" name="next" value="{{next}}" />
                                </div>

                                <label for="id_releasedate" class="control-label ">
                                    Releasedate - <span class="small text-light">YEAR/MM/DD</span>
                                </label>

                                <div class="controls">
                                    <div class="form-group">
                                        {{ form.releasedate|attr:"class:form-control"|attr:"id=id_releasedate"|attr:"required" }}
                                    </div>
                                    <input type="hidden" name="next" value="{{next}}" />
                                </div>


                                <label for="id_price" class="control-label requiredField">
                                    Price<span class="asteriskField">*</span>
                                </label>

                                <div class="controls">
                                    <div class="form-group">
                                        {{ form.price|attr:"class:form-control"|attr:"step=0.01"|attr:"type:number"|attr:"class=numberinput"|attr:"id=id_price"|attr:"required" }}
                                    </div>
                                    <input type="hidden" name="next" value="{{next}}" />
                                </div>


                                <label for="id_rating" class="control-label ">
                                    Rating
                                </label>

                                <div class="controls">
                                    <div class="form-group">
                                        {{ form.rating|attr:"class:form-control"|attr:"step=0.01"|attr:"type:number"|attr:"class=numberinput"|attr:"id=id_rating" }}
                                    </div>
                                    <input type="hidden" name="next" value="{{next}}" />
                                </div>

                                <label for="id_image_url" class="control-label ">
                                    Image url
                                </label>

                                <div class="controls">
                                    <div class="form-group ">
                                        {{ form.image_url|attr:"class:form-control"|attr:"maxlength=1024"|attr:"type:url"|attr:"name=image_url"|attr:"id=id_image_url"|attr:"urlinput" }}
                                    </div>
                                    <input type="hidden" name="next" value="{{next}}" />
                                </div>

                            </div>

                            <label for="id_new-image" class="control-label ">
                                Select Image
                            </label>
                            <input id="new-image" type="file" name="image" accept="image/*"
                                    class="btn btn-outline-grey border-q rounded-2">
                            <strong>
                                <p class="text-danger" id="filename"></p>
                            </strong>

                            <div id="div_id_is_new_release" class="control-group">
                                <div class="controls">
                                    <label for="id_is_new_release" class="checkbox ">
                                        <input type="checkbox" name="is_new_release"
                                            class="border-black rounded-0 checkboxinput" id="id_is_new_release">
                                        Is New Release - <span class="small text-light">For NEW Label.</span>
                                    </label>
                                </div>
                            </div>

                            <div id="div_id_is_deal" class="control-group">
                                <div class="controls">
                                    <label for="id_is_deal" class="checkbox ">
                                        <input type="checkbox" name="is_deal"
                                            class="border-black rounded-0 checkboxinput" id="id_is_deal">
                                        Is Deal - <span class="small text-light">For DEAL Label.</span>
                                    </label>
                                </div>
                            </div>

                            <div id="div_id_is_clearance" class="control-group">
                                <div class="controls">
                                    <label for="id_is_clearance" class="checkbox ">
                                        <input type="checkbox" name="is_clearance"
                                            class="border-black rounded-0 checkboxinput" id="id_is_clearance">
                                        Is Clearance
                                    </label>
                                </div>
                            </div>
                            <div class="text-right">
                                <a class="btn btn-outline-warning border-q rounded-2" href="/records/">Cancel</a>
                                <button class="btn btn-outline-success border-q rounded-2" type="submit">Add
                                    record</button>
                            </div>
                        </form>

                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

records/templates/records/edit_record.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 mx-auto">
            <div class="product-details-container mb-5 mt-md-5">

                <p class="lead font-weight-bold">Edit record</p>

                <div class="col-12">

                <form method="POST" action="{% url 'edit_record' record.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}

                    <label for="id_category" class="control-label ">
                        Category
                    </label>
                    <p class="small text-light">Hold down CTRL to mark more than one category.</p>

                    <div class="controls">
                        <div class="form-group">
                            {{ form.category|attr:"class:form-control"|attr:"class:selectmultiple"|attr:"name=category"|attr:"id=id_category" }}
                        </div>                                   
                    </div>

                    <label for="id_sku" class="control-label ">
                        Sku
                    </label>
                    <div class="form-group">
                        {{ form.sku|attr:"class:form-control"|attr:"placeholder:"|attr:"id=id_sku" }}
                    </div>
                    <input type="hidden" name="next" value="{{next}}" />

                    <label for="id_name" class="control-label requiredField">
                        Name<span class="asteriskField">*</span>
                    </label>
                    <div class="form-group">
                        {{ form.name|attr:"class:form-control"|attr:"placeholder:"|attr:"id=id_name"|attr:"required" }}
                    </div>
                    <input type="hidden" name="next" value="{{next}}" />

                    <label for="id_description" class="control-label requiredField">
                        Description<span class="asteriskField">* </span> <span class="small text-light"> HTML here is ok.</span>
                    </label>

                    <div class="controls">
                        <div class="form-group">
                            {{ form.description|attr:"class:form-control"|attr:"cols:40"|attr:"rows=10"|attr:"id=id_description"|attr:"required" }}
                        </div>
                        <input type="hidden" name="next" value="{{next}}" />
                    </div>

                    <label for="id_releasedate" class="control-label ">
                        Releasedate - <span class="small text-light">YEAR/MM/DD</span>
                    </label>

                    <div class="controls">
                        <div class="form-group">
                            {{ form.releasedate|attr:"class:form-control"|attr:"id=id_releasedate"|attr:"required" }}
                        </div>
                        <input type="hidden" name="next" value="{{next}}" />
                    </div>


                    <label for="id_price" class="control-label requiredField">
                        Price<span class="asteriskField">*</span>
                    </label>

                    <div class="controls">
                        <div class="form-group">
                            {{ form.price|attr:"class:form-control"|attr:"step=0.01"|attr:"type:number"|attr:"class=numberinput"|attr:"id=id_price"|attr:"required" }}
                        </div>
                        <input type="hidden" name="next" value="{{next}}" />
                    </div>


                    <label for="id_rating" class="control-label ">
                        Rating
                    </label>

                    <div class="controls">
                        <div class="form-group">
                            {{ form.rating|attr:"class:form-control"|attr:"step=0.01"|attr:"type:number"|attr:"class=numberinput"|attr:"id=id_rating" }}
                        </div>
                        <input type="hidden" name="next" value="{{next}}" />
                    </div>             

                    <div>
                        {% for field in form %}
                            {% if field.name == 'image' %}
                                    {{ field }}
                                {% endif %}
                        {% endfor %}
                        <label for="id_new-image" class="control-label ">
                            Select Image
                        </label>
                    </div>

                    <div id="div_id_is_new_release" class="control-group">
                        <div class="controls">
                            <label for="id_is_new_release" class="checkbox ">
                                <input type="checkbox" name="is_new_release"
                                    class="border-black rounded-0 checkboxinput" id="id_is_new_release">
                                Is New Release - <span class="small text-light">For NEW Label.</span>
                            </label>
                        </div>
                    </div>
    
                    <div id="div_id_is_deal" class="control-group">
                        <div class="controls">
                            <label for="id_is_deal" class="checkbox ">
                                <input type="checkbox" name="is_deal"
                                    class="border-black rounded-0 checkboxinput" id="id_is_deal">
                                Is Deal - <span class="small text-light">For DEAL Label.</span>
                            </label>
                        </div>
                    </div>
    
                    <div id="div_id_is_clearance" class="control-group">
                        <div class="controls">
                            <label for="id_is_clearance" class="checkbox ">
                                <input type="checkbox" name="is_clearance"
                                    class="border-black rounded-0 checkboxinput" id="id_is_clearance">
                                Is Clearance - <span class="small text-light">For CLEARANCE Label.</span>
                            </label>
                        </div>
                    </div>
                    
    
                        <div class="text-right">
                            <a class="btn btn-outline-warning border-q rounded-2" href="{% url 'records' %}">Cancel</a>
                            <button class="btn btn-outline-success border-q rounded-2" type="submit">Update Record</button>
                        </div>
                    </form>

                </div>
                
            </div>            
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

records/templates/records/record_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                    {% if record.image %}
                        <a href="{{ record.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid shadow-img" src="{{ record.image.url }}" alt="{{ record.name }}">
                        </a>
                        {% else %}
                        <a href="">
                            <img class="card-img-top img-fluid shadow-img" src="{{ MEDIA_URL }}noimage.png" alt="{{ record.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    <p class="mb-0">{{ record.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">${{ record.price }}</p>
                    {% if record.rating %}
                        <small class="text-light"><i class="fas fa-star mr-1"></i>{{ record.rating }} / 5</small>
                    {% else %}
                        <small class="text-light">No Rating</small>
                    {% endif %}
                    <small class="text-light">
                        <i class="fa-solid fa-folder-open"></i> 
                        {% for category in record.category.all %}
                            <a class="nav-color" href="{% url 'records' %}?category={{ category.name }}">{{ category.get_friendly_name }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </small>     

                    <!-- CRUD FOR SU -->
                    {% if request.user.is_superuser %}
                    <p class="mb-0">
                    <small class="ml-3">
                        <a href="{% url 'edit_record' record.id %}"><i class="fas fa-edit"></i> Edit</a> | 
                        <a class="text-danger" href="{% url 'delete_record' record.id %}"><i class="fas fa-trash"></i> Delete</a>
                    </small>
                    </p>
                    {% endif %}

                    <p class="mt-3">{{ record.description|safe|linebreaksbr }}</p>

                    <form class="form" action="{% url 'add_to_bag' record.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-outline-grey border-q rounded-2" 
                                                data-item_id="{{ record.id }}" id="decrement-qty_{{ record.id }}" aria-label="decrement">
                                                <i class="fas fa-minus"></i> 
                                            </button>
                                        </div>
                                        <input class="form-control qty_input border-q" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ record.id }}"
                                            id="id_qty_{{ record.id }}" aria-label="quantity">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-outline-grey border-q rounded-2"
                                                data-item_id="{{ record.id }}" id="increment-qty_{{ record.id }}" aria-label="increment">
                                                    <i class="fas fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-12">
                                <a href="{% url 'records' %}" class="btn btn-outline-warning border-q rounded-2 mt-5"> 
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <input type="submit" class="btn border-q btn-outline-primary rounded-2 text-uppercase mt-5" value="Add to Bag">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'records/includes/quantity_input_script.html' %}
{% endblock %}